# Generated by Django 3.2.7 on 2021-09-12 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "column_separator",
                    models.CharField(
                        choices=[
                            (",", "Comma (,)"),
                            (";", "Semicolon (;)"),
                            ("|", "Pipe (|)"),
                        ],
                        default=",",
                        max_length=1,
                    ),
                ),
                (
                    "string_characters",
                    models.CharField(
                        choices=[("'", "Single-quote (')"), ('"', 'Double-quote (")')],
                        default='"',
                        max_length=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Ready", "Ready"), ("Processing", "Processing")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("csv_file", models.FileField(upload_to="")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_datasets",
                        to="schemas.schema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Full name", "Full name"),
                            ("Email", "Email"),
                            ("Job", "Job"),
                            ("Company", "Company"),
                            ("Integer", "Integer"),
                        ],
                        default="Full name",
                        max_length=9,
                    ),
                ),
                ("start_value", models.IntegerField(blank=True, null=True)),
                ("end_value", models.IntegerField(blank=True, null=True)),
                ("order", models.PositiveIntegerField()),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schema_columns",
                        to="schemas.schema",
                    ),
                ),
            ],
        ),
    ]
