# Generated by Django 3.2.7 on 2021-09-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_alter_dataset_csv_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schema',
            old_name='string_characters',
            new_name='string_character',
        ),
    ]
