# Generated by Django 3.2.7 on 2021-09-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_alter_dataset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)'), ('|', 'Pipe (|)')], default=';', max_length=1),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[("'", "Single-quote (')"), ('"', 'Double-quote (")')], default="'", max_length=1),
        ),
    ]
